set top_name msr_transient_batch_bench_kernel
set project_name transient_batch_bench_600x1_10ns_sharedfp
set clock_period 20
set source_file msr_vitis_kernel.cpp
set cflags {-std=c++11 -DMSR_CROSS_SECTION_LANE_FACTOR=1 -DMSR_NEUTRONICS_LANE_FACTOR=1 -DMSR_THERMAL_LANE_FACTOR=1 -DMSR_HEAT_EXCHANGER_LANE_FACTOR=1 -DMSR_FIXED_CORE_N=200 -DMSR_FIXED_BOP_NX=200 -DMSR_FIXED_HARDWARE_SUBSTEPS=32 -DMSR_MAX_STATE_N=200 -DMSR_MAX_TRANSIENT_STEPS=600 -DMSR_MAX_BATCH_SCENARIOS=1 -DMSR_BATCH_BENCH_STEP_COUNT=600 -DMSR_BATCH_BENCH_SCENARIO_COUNT=1 -DMSR_RESIDENT_THERMAL_FLOAT=1 -DMSR_RESIDENT_HISTORY_FLOAT=1 -DMSR_BATCH_CONTROL_FLOAT=1 -DMSR_PRECURSOR_ANALYTIC_UPDATE=1 -DMSR_POINT_KINETICS_SOLVER=1 -DMSR_SHARED_FPU_MODE=1}
source [file join [file normalize [file dirname [info script]]] hls_export_common.tcl]
